### ISSUE TITLE
RPhylotastic ready for phylotastic manuscript

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylotastic#204]
Due 6/15/2018. 

- [x] package is accessible
- [x] package auto-installs
- [x] documentation matches functionality
- [x] vignettes work
   - [x] fix commented out parts 
   - [x] s/taxon_get_species_from_/taxon_get_species_and_/
   - [x] phylo_compare is supposed to be newick_compare?  
- [x] add @LunaSare to list of authors
- [x] the long URL in DESCRIPTION is causing a wrap failure in the PDF docs.  Replace with www.phylotastic.org?

**Comment by arlin** [comment]
@bomeara you are not exporting get_base_url.  Is that deliberate?

**Comment by LunaSare** [comment]
I changed `newick_compare` to `phylo_compare`, since it was not taking newick trees as input but phylo R objects. If people want it to take newick trees instead of R objects as input, or both, I can do that. 
For datelife we are making all functions so that they can take newick trees or phylo R objects (or a list of taxa too, depending on the function).

**Comment by LunaSare** [comment]
Vignette is working! I just wanna add a better list management example to it @arlin, but I'm not sure how to get a token to do that.

**Comment by arlin** [comment]
@LunaSare, if you have done everything listed on this ticket, you can close it.
